import { IGymEquipmentRepository } from "../../domain/repositories/IGymEquipmentRepository.js";
import { GymEquipment } from "../../domain/entities/GymEquipment.js";
import { CreateGymEquipmentDTO } from "../dtos/GymEquipmentDTO.js";

export class CreateGymEquipmentUseCase {
    constructor(private gymEquipmentRepository: IGymEquipmentRepository) { }

    async execute(dto: CreateGymEquipmentDTO): Promise<GymEquipment> {
        const equipment = new GymEquipment(
            'temp', // ID generated by DB
            dto.gymId,
            dto.name,
            dto.photoUrl || '',
            dto.windowTime,
            dto.condition || 'good',
            false
        );
        return this.gymEquipmentRepository.create(equipment);
    }
}
