import { IGymPlanRepository } from "../../domain/repositories/IGymPlanRepository.js";
import { GymPlan } from "../../domain/entities/GymPlan.js";
import { GymPlanModel, IGymPlanDocument } from "../database/mongoose/GymPlanSchema.js";
import { GymPlanPersistenceMapper } from "../mappers/GymPlanPersistenceMapper.js";
import mongoose from "mongoose";

export class GymPlanRepositoryImpl implements IGymPlanRepository {
    async create(plan: GymPlan): Promise<GymPlan> {
        // Since Entity usually has an ID generated by Domain or we let DB generate it.
        // If Entity comes with ID (e.g. UUID), we use it. If Mongoose ObjectId, we might need to handle it.
        // Here we assume standard flow: Entity is created with a placeholder ID or we let Mongoose generate.
        // But `GymPlan` entity constructor requires ID.
        // Let's assume the UseCase generates ID? Or we omit ID in persistence creation?
        // Simple way: Let Mongoose generate _id.

        const persistenceData = {
            gymId: new mongoose.Types.ObjectId(plan.gymId),
            planName: plan.planName,
            type: plan.type,
            monthlyFee: plan.monthlyFee,
            ...(plan.durationInDays !== undefined ? { durationInDays: plan.durationInDays } : {}),
            ...(plan.description !== undefined ? { description: plan.description } : {}),
            isDelete: plan.isDelete
        };

        const doc = await GymPlanModel.create(persistenceData);
        return GymPlanPersistenceMapper.toDomain(doc);
    }

    async findById(id: string): Promise<GymPlan | null> {
        const doc = await GymPlanModel.findById(id);
        if (!doc) return null;
        return GymPlanPersistenceMapper.toDomain(doc);
    }

    async findByGymId(gymId: string): Promise<GymPlan[]> {
        const docs = await GymPlanModel.find({ gymId: gymId, isDelete: false }); // Only return non-deleted plans
        return docs.map(doc => GymPlanPersistenceMapper.toDomain(doc));
    }

    async update(plan: GymPlan): Promise<GymPlan> {
        const persistenceData = GymPlanPersistenceMapper.toPersistence(plan);
        // We exclude _id from update payload usually, but findByIdAndUpdate ignores it in $set if not specified explicitly?
        // Safer to construct update payload.

        const updatePayload: any = {
            planName: plan.planName,
            monthlyFee: plan.monthlyFee,
            durationInDays: plan.durationInDays,
            description: plan.description,
            isDelete: plan.isDelete,
            updatedAt: new Date()
        };

        const updatedDoc = await GymPlanModel.findByIdAndUpdate(
            plan.id,
            updatePayload,
            { new: true }
        );

        if (!updatedDoc) throw new Error("GymPlan not found for update");
        return GymPlanPersistenceMapper.toDomain(updatedDoc);
    }
}
